conf/ini-files/Arabidopsis_thaliana.ini, conf/ini-files/Medicago_truncatula.ini, conf/ini-files/Oryza_brachyantha.ini, conf/ini-files/Setaria_italica.ini, conf/ini-files/Solanum_lycopersicum.ini, conf/ini-files/Solanum_tuberosum.ini, conf/ini-files/Sorghum_bicolor.ini, conf/ini-files/Triticum_aestivum.ini
based on the list available here http://pathway.gramene.org/
=> fixing and adding GRAMENE_PATHWAY links for plants

conf/ini-files/Arabidopsis_thaliana.ini, conf/ini-files/DEFAULTS.ini
Adding in sources here because I removed them from common here:
https://github.com/EnsemblGenomes/eg-web-common/pull/8
=> moving plant specific sources here from 'common'

conf/ini-files/Hordeum_vulgare.ini, conf/ini-files/Leersia_perrieri.ini, conf/ini-files/Oryza_barthii.ini, conf/ini-files/Oryza_brachyantha.ini, conf/ini-files/Oryza_glaberrima.ini, conf/ini-files/Oryza_glumaepatula.ini, conf/ini-files/Oryza_meridionalis.ini, conf/ini-files/Oryza_nivara.ini, conf/ini-files/Oryza_punctata.ini, conf/ini-files/Oryza_rufipogon.ini, conf/ini-files/Oryza_sativa.ini
Modified .ini files to add two RNA-Seq experiments to H_vul, and update menu organization + descriptions for a number of Oryza_ species' RNA-Seq experiments
=> Updates for plant RNA-seq experiments

conf/ini-files/Oryza_glaberrima.ini
Can you deploy this on test.plants? If it looks OK, I'll push to master.
=> adding the variation db to O. glab

conf/ini-files/Triticum_aestivum.ini
I updatedv Triticum_aestivum ini file for the new wheat production site
=> Updated BED files and removed alignments

conf/ini-files/Triticum_aestivum.ini
I disabled all the BAM and BED files tracks
=> disabled tracks until bug is fixed

conf/ini-files/Triticum_aestivum.ini
Removed comments so attached BED files can be viewed
=> removed comments for methylation

conf/ini-files/Triticum_aestivum.ini
I updated the wheat INI file with aligned BAM files
=> Adding BAM alignment files to wheat

conf/ini-files/Triticum_aestivum.ini
I added an attached track hub example in the wheat ini file
=> Adding track hub example

conf/ini-files/DEFAULTS.ini, conf/ini-files/arabidopsis_lyrata.ini, conf/ini-files/arabidopsis_thaliana.ini, conf/ini-files/prunus_persica.ini, conf/ini-files/trifolium_pratense.ini
Sorry for late testing!
Please can you repack after pulling?
=> More config tinkering to pull

conf/json/oryza_sativa_vcf.json
In our production environment these files are this folder:
/nfs/ensemblgenomes/ftp/pub/misc_data/vcf/oryza_sativa/
I guess you need to copy them over to your chosen partition, let me know if you need anything else,
Bruno
=> use local files instead of remote ftp:// paths for oryza VCF files

conf/json/triticum_aestivum_vcf.json
=> adding attached VCF for wheat

conf/json/malus_domestica_vcf.json, conf/json/oryza_sativa_vcf.json, conf/json/triticum_aestivum_vcf.json
Hi, this is a new JSON file for apple (malus_domestica) variants in attached VCF form.
It has been tested on a sandbox.
=> added apple attached VCF config

conf/json/malus_domestica_vcf.json
Fix config for malus_domestica to use data from the data_files folder (introduced in https://github.com/EnsemblGenomes/eg-web-plants/pull/28).
=> Fix config json for malus_domestica

conf/json/triticum_aestivum_vcf.json
Hi, fix to the issue reported in https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5562
=> fixed wheat paths

htdocs/info/about/collaborations/gramene.html, htdocs/info/about/collaborations/panoryza.html
Hi @ens-ap5 @azangru @gnaamati ,
this PR contains updated content for plant collaborators, including new references, a new project (PanOryza) and a missing Gramene logo.
I am not sure whether panoryza.html needs to be added to some index, or whether that's picked up by the code. Please let me know about that and thanks for your help,
Bruno
=> Updated collaborations content

conf/ini-files/arabidopsis_thaliana.ini
=> fixed broken url

conf/json/cucumis_sativus_vcf.json, conf/json/lactuca_sativa_vcf.json, conf/json/theobroma_cacao_vcf.json
Added 3 new conf files for EVA DBs
=> new EVA DBs for 107

conf/json/cucumis_sativus_vcf.json, conf/json/lactuca_sativa_vcf.json, conf/json/theobroma_cacao_vcf.json
Updated paths to attached VCF files
=> updated links to files

htdocs/Triticum_aestivum_strains.inc
Update the header text on the page listing triticum aestivum cultivars, as per [ENSWEB-6850](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6850).
=> Update header text in cultivars page

conf/json/eragrostis_tef_vcf.json
Updated the JSON file to local
=> fixed json file to local

conf/json/triticum_aestivum_vcf.json
The information for the watkins has been added in the file _triticum_aesticum_vcf.json_.
=> Updating triticum_aesticum_vcf.json

htdocs/Triticum_aestivum_strains.inc
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6956
Sandbox link: http://wp-np2-1e.ebi.ac.uk:9410/Triticum_aestivum/Info/Cultivars
=> Update rice cultivar info

conf/json/oryza_sativa_vcf.json
Updating the oryza_sativa.json file by adding the rice 3k VCF file information.
=> Updating oryza_sativa.json

conf/SiteDefs.pm
This MR disables HMMR 
https://embl.atlassian.net/browse/ENSINT-2447
=> Disable HMMR

htdocs/info/genome/compara/homology_method.html, htdocs/info/genome/compara/homology_types.html
This PR updates Plants specific details to the homology methods and types doc.
=> Doc Update: Plants specific updates to homology methods and types doc
