conf/ini-files/Zea_mays.ini
there is a missing / on one of the bigBed file url. 
http:/brie.cshl.edu/data/Zea_mays/HC-lncRNAs.bb
changed to
http://brie.cshl.edu/data/Zea_mays/HC-lncRNAs.bb
=> fix a typo on the url

conf/json/arabidopsis_thaliana_vcf.json
Hi @nicklangridge, here is the patch we discussed. The new file exists at that location, along with a similarly named TBI file.
=> fix the path for the arabidopsis VCF file

conf/ini-files/arabidopsis_thaliana.ini
NASC-related ENSEMBL_EXTERNAL_URLS have been commented out as deprecated
=> commented out deprecated NASC URLs in arabidopsis_thaliana

conf/json/triticum_aestivum_vcf.json
Similar to https://github.com/EnsemblGenomes/eg-web-plants/pull/29, but this time fixing the config for Triticum aestivum (bug introduced in https://github.com/EnsemblGenomes/eg-web-plants/pull/28).
=> Fix config for Triticum aestivum

conf/ini-files/beta_vulgaris.ini
HI @ens-ap5 @gnaamati , following @james-monkeyshines reporting https://www.ebi.ac.uk/panda/jira/browse/ENSINT-492 , this edit attempts to solve the problem for beta_vulgaris .
It might well be that we have to do similarly for other species.
Let me know if the syntax is not correct, thanks,
Bruno
=> added NCBI URL instead of ENA

htdocs/Brassica_rapa_strains.inc, htdocs/Olea_europaea_strains.inc, htdocs/info/about/collaborations/gramene.html, htdocs/info/genome/annotation/repeat_features.html
HI @ens-ap5 @ens-ds23 @gnaamati ,
this PR adds 
1. plant-specific documentation for the annotation of repeats that matches the contents of release 52/105. I am hoping this will show up as http://plants.ensembl.org/info/genome/annotation/repeat_features.html
2. blurbs for strain summaries
Please let me know if you see anything wrong,
Bruno
=> updated annotation of repeats docs and strain blurbs for release 52/105

htdocs/Triticum_aestivum_strains.inc
I have updated the wheat strain info page according to [ENSWEB-6371](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6371). My sandbox link with this update is at: http://wp-np2-1e.ebi.ac.uk:9310/Triticum_aestivum/Info/Strains?db=core
=> Update wheat strain view static content for 105

htdocs/info/genome/compara/Ortholog_qc_manual.html
[Public plugins PR 651](https://github.com/Ensembl/public-plugins/pull/651) has been submitted to update the high-confidence orthologies section of Vertebrates Compara documentation.
This PR would update the corresponding Plants Compara documentation with equivalent changes.
=> Orthology documentation update for Plants

htdocs/info/genome/compara/multiple_genome_alignments.html
This adds documentation on the Cactus alignment method to the Ensembl Plants webpage showing the list of multiple genome alignments ([here](http://plants.ensembl.org/info/genome/compara/multiple_genome_alignments.html)).
(Cactus alignments were introduced to the Ensembl Plants in e110.)
=> Add docs for Cactus alignment method

modules/EnsEMBL/Web/Component/Compara_Alignments.pm
This PR would continue to hide the placeholder tree mediating access to the 16 Wheat Cactus alignment. (See [ENSWEB-6844](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6844)).
Example alignment region on sandbox: http://wp-np2-25.ebi.ac.uk:5098/Triticum_aestivum/Location/Compara_Alignments?align=313160;db=core;r=3D:2634350-2634543
=> Hide placeholder tree for Wheat Cactus alignment

conf/SiteDefs.pm
Adding `vicia_faba` to the `SiteDefs::PRODUCTION_NAMES` config variable would enable newly introduced species Vicia faba to be accessed on the Ensembl Plants 112 staging site.
Related links:
- Vicia faba page on Ensembl Plants 112 staging site: https://staging-plants.ensembl.org/Vicia_faba/Info/Index
- Vicia faba page on a Plants sandbox: http://wp-np2-25.ebi.ac.uk:5098/Vicia_faba/Info/Index
=> Add vicia_faba to SiteDefs::PRODUCTION_NAMES

conf/SiteDefs.pm
Adding `aegilops_umbellulata` to the `SiteDefs::PRODUCTION_NAMES` config variable would enable newly introduced species _Aegilops umbellulata_ to be accessed on the Ensembl Plants 112 RC site.
Related links:
- Aegilops umbellulata page on Ensembl Plants 112 RC site: https://rc-plants.ensembl.org/Aegilops_umbellulata/Info/Index
- Aegilops umbellulata page on a Plants sandbox: http://wp-np2-25.ebi.ac.uk:5098/Aegilops_umbellulata/Info/Index
=> Add aegilops_umbellulata to SiteDefs::PRODUCTION_NAMES

modules/EnsEMBL/Web/ConfigPacker.pm
- Filling out the template is required. Any pull request that does not include enough information to be efficiently reviewed may be rejected.
- Please consider which branch this is to be submitted against. This is usually obvious, however if it is to be applied to both a release branch nn and master then please submit it against postreleasefix/nn and let us merge it into to the two branches.
In conjunction with [ensembl-webcode PR 1017](https://github.com/Ensembl/ensembl-webcode/pull/1017), this PR (for the `release/eg/59` branch only) makes it possible to suppress the Wheat Cactus alignment on the Ensembl Plants 112 site.
To take effect, it is necessary to repack the `MULTI` packed file.
This change has the effect of making the Wheat Cactus alignment disappear from the Wheat genomic …
=> Hide Wheat Cactus alignments

modules/EnsEMBL/Web/Component/Compara_Alignments.pm
This PR would continue to hide the placeholder tree mediating access to the 16 Wheat Cactus (now `CACTUS_DB`) alignment. (See [ENSWEB-6844](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6844)).
Example alignment region on sandbox: http://wp-np2-25.ebi.ac.uk:5098/Triticum_aestivum/Location/Compara_Alignments?align=314995;db=core;r=3D:2634350-2634543
=> Hide placeholder tree for Wheat CACTUS_DB alignment

modules/EnsEMBL/Web/ImageConfig/alignsliceviewbottom.pm
Wheat Cactus alignments are taking time to load on the Ensembl Plants website.
This PR aims to reduce the loading time of the Wheat Cactus alignment by switching off alternative gene model tracks by default.
This PR affects the Wheat Cactus image alignment in the Ensembl Plants website, switching off alternative gene model tracks by default, and noticeably reducing the load time.
Example: [sandbox](http://wp-np2-25.ebi.ac.uk:5098/Triticum_aestivum_landmark/Location/Compara_Alignments/Image?r=6B:570561430-570611430;db=core;align=314995) vs [RC site](https://rc-plants.ensembl.org/Triticum_aestivum_landmark/Location/Compara_Alignments/Image?r=6B:570561430-570611430;db=core;align=314995)
Because the changes in this PR are restricted to the Wheat `CACTUS_DB` image alignment on the Ensembl …
=> Hide alt gene tracks in Wheat Cactus image align view

modules/EnsEMBL/Web/Component/Compara_AlignSliceSelector.pm
This PR would have the effect of hiding the Wheat Cactus alignment for non-polyploid genomes.
Because of the way Wheat Cactus alignment data was loaded, there is an imbalance in the number of alignment blocks in polyploid and non-polyploid genomes, leading to excessive load times affecting the latter.
Example: [sandbox](http://wp-np2-25.ebi.ac.uk:5098/Hordeum_vulgare/Location/View?r=6H:21859180-21859461) vs [RC site](http://rc-plants.ensembl.org/Hordeum_vulgare/Location/View?r=6H:21859180-21859461)
=> Hide Wheat Cactus alignment for non-polyploid genomes

conf/ini-files/vitis_vinifera.ini
This configures Ensembl Plants eg61/e114 with the updated version of Vitis vinifera.
Vitis vinifera example links:
- Ensembl Plants staging: https://staging-plants.ensembl.org/Vitis_vinifera/Info/Index
- Ensembl Plants sandbox: http://wp-np2-25.ebi.ac.uk:5098/Vitis_vinifera/Info/Index
=> Update release version of vitis_vinifera for eg61

htdocs/info/genome/compara/ancestral_sequences.html
This pull request would add an ancestral sequences page — much like [its counterpart in the Ensembl Vertebrates website](https://github.com/Ensembl/public-plugins/blob/7cfaaa40d33e8c5cb45371a8866a797f4131face/ensembl/htdocs/info/genome/compara/ancestral_sequences.html) — to the Ensembl Plants web docs.
This would effectively mend the broken link in the [Rice EPO text alignment](https://plants.ensembl.org/Oryza_sativa/Location/Compara_Alignments?r=5:20683551-20684336) offering information about [how ancestral sequences are calculated](https://plants.ensembl.org/info/genome/compara/ancestral_sequences.html):
=> Add ancestral sequences page to Plants web docs

modules/EnsEMBL/Web/ConfigPacker.pm
This pull request would set the `STRAIN_GROUP` of `hordeum_vulgare_goldenmelon` in the Plants `ConfigPacker` module, ensuring consistent handling of this Barley cultivar in web views.
This PR has been submitted against the `release/eg/61` branch: this is a proposed solution for release e114/eg61 only, in the expectation that a more effective solution will be implemented for this Barley cultivar from release e115/eg62 onwards.
This change would affect the [Barley cultivar list view](https://rc-plants.ensembl.org/Hordeum_vulgare/Info/Cultivars?db=core) and any view relying on the `STRAIN_GROUP` metadata for correct handling of Barley cultivars.
Example Barley cultivar list view before change:
Example Barley cultivar list view after change:
=> Set hordeum_vulgare_goldenmelon strain group in Plants ConfigPacker

htdocs/info/genome/compara/epo_anchors_info.html, htdocs/info/genome/compara/multiple_genome_alignments.html
In conjunction with [public-plugins PR 900](https://github.com/Ensembl/public-plugins/pull/900) and [eg-web-metazoa PR 50](https://github.com/EnsemblGenomes/eg-web-metazoa/pull/50), this PR would update the multiple genome alignment documentation, with a particular focus on Cactus alignments.
It would also add page `epo_anchors_info.html` to Ensembl Plants docs.
Example on Plants sandbox: http://wp-np2-35.ebi.ac.uk:5098/info/genome/compara/multiple_genome_alignments.html
=> Update Plants multiple genome alignment docs

htdocs/info/genome/compara/homology_method.html
This PR would make a correction in a note of the storage of between-species paralogies, making it consistent with Vertebrates and general non-vertebrate documentation.
=> Update text about between-species paralogies

htdocs/info/genome/compara/conservation_and_constrained.html
This PR adds documentation on conservation scores and constrained elements to Ensembl Plants.
As well as providing information relevant to data associated with the rice EPO_EXTENDED alignments, it supports [ensembl-webcode PR 1110](https://github.com/Ensembl/ensembl-webcode/pull/1110), ensuring that the link in the descriptions of conservation-score and constrained-element tracks on the Ensembl Plants site can point to Plants-specific documentation.
=> Add conservation docs for Ensembl Plants
